# GuruShots Collection Strategies Configuration
# Format: action, interval, from_time, to_time

[collecte-till-1h]
description="collecte jusqu'à 1 heure de la fin"
0="collecte, next-15m, now, 1h:0m:0s"

[collecte-last-hour] 
description="collecte jusqu'à 10 minutes de la fin"
0="collecte, next-5m, 1h:0m:0s, 0h:10m:0s"

[collecte-last-10-minutes]
description="collecte jusqu'à 1 minute de la fin" 
0="collecte, next-1m, 0h:10m:0s, 0h:1m:0s"

[collecte-last-1-minute]
description="collecte jusqu'à la fin"
0="collecte, next-10s, 0h:1m:0s, 0h:0m:0s"